// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HashingPwInterface is an autogenerated mock type for the HashingPwInterface type
type HashingPwInterface struct {
	mock.Mock
}

// CheckPassword provides a mock function with given fields: inputPw, currentPw
func (_m *HashingPwInterface) CheckPassword(inputPw []byte, currentPw []byte) error {
	ret := _m.Called(inputPw, currentPw)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(inputPw, currentPw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GeneretePassword provides a mock function with given fields: currentPw
func (_m *HashingPwInterface) GeneretePassword(currentPw string) ([]byte, error) {
	ret := _m.Called(currentPw)

	if len(ret) == 0 {
		panic("no return value specified for GeneretePassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(currentPw)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(currentPw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(currentPw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHashingPwInterface creates a new instance of HashingPwInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashingPwInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashingPwInterface {
	mock := &HashingPwInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
